# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build for testing"
  lane :build do
    scan(
      build_for_testing: true,
      scheme: "CILab")
  end

  desc "CI Build for testing"
  lane :ci_build do
    scan(
      build_for_testing: true,
      derived_data_path: "./output/derived_data",
      output_directory: "./output/",
      output_xctestrun: true,
      scheme: "CILab")
  end

  desc "Run unit tests"
  lane :unit_test do
    scan(
      scheme: "CILab",
      test_without_building: true)
  end

  desc "CI Run unit tests"
  lane :ci_unit_test do
    scan(
      derived_data_path: "./input/derived_data",
      result_bundle_path: "./input/CILab.xcresult",
      scheme: "CILab",
      test_without_building: true)
  end
end
