name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Show runner info
        run: echo ${{ runner }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: fastlane build
      - name: Show result
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: CILab.xcresult
        if: success() || failure()
