name: Test suite
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

jobs:
  build:
    name: "Build for testing"
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: fastlane ci_build
      - name: Zip derived data
        if: ${{ success() }}
        run: zip derived_data.zip ./derived_data/* -r
      - name: Upload derived data
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: derived_data.zip
          path: derived_data.zip

  unit_test:
    name: "Run unit tests"
    needs: build
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download derived data
        uses: actions/download-artifact@v3
        with:
          name: derived_data.zip
      - name: Unzip derived data
        run: unzip derived_data.zip -d ./
      - name: Run unit tests
        run: fastlane ci_unit_test
      - name: Report test results
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: ./output/CILab.xcresult
      - name: Upload test results
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: CILab.xcresult
          path: ./output/CILab.xcresult
          if-no-files-found: error
