name: Test suite
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: fastlane build
      - name: Upload test bundle
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-bundle
          path: fastlane/test_output/CILab.xctest
          if-no-file-found: error

  unit_test:
    runs-on: macos-13
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run unit tests
        run: fastlane unit_test
      - name: Report test results
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: CILab.xcresult
        if: success() || failure()
