name: Test suite
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

jobs:
  build:
    name: "Build for testing"
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: fastlane ci_build
      - name: Zip outputs
        if: ${{ success() }}
        run: zip output.zip ./output/* -r
      - name: Upload outputs
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: output.zip
          path: output.zip

  unit_test:
    name: "Run unit tests"
    needs: build
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download inputs
        uses: actions/download-artifact@v3
        with:
          name: inputs.zip
      - name: Unzip derived data
        run: unzip ./inputs.zip -d ./input
      - name: Display structure of downloaded files
        run: ls
        working-directory: input
      - name: Run unit tests
        run: fastlane ci_unit_test
      - name: Report test results
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: ./builds/CILab.xcresult
      - name: Upload test results
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: CILab.xcresult
          path: ./builds/CILab.xcresult
          if-no-files-found: error
