name: Test suite
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  DELELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

jobs:
  build:
    name: "Build for testing"
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: fastlane ci_build
      - name: Upload result bundle
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-bundle
          path: builds/build.xcresult
          if-no-files-found: error

  unit_test:
    name: "Run unit tests"
    needs: build
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run unit tests
        run: fastlane ci_unit_test
      - name: Report test results
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: CILab.xcresult
        if: success() || failure()
