name: Test suite
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  DELELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

jobs:
  build:
    name: "Build for testing"
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: fastlane ci_build
      - name: Upload test bundle
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: CILab.xcresult
          path: builds/CILab.xcresult
          if-no-files-found: error
      - name: Zip derived data
        if: ${{ success() }}
        run: zip builds/derived_data.zip ./derived_data/* -r
      - name: Upload dervied data
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: derived_data.zip
          path: builds/derived_data.zip

  unit_test:
    name: "Run unit tests"
    needs: build
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download test bundle
        uses: actions/download-artifact@v3
        with:
          name: CILab.xcresult
          path: builds/CILab.xcresult
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: builds
      - name: Download derived data
        uses: actions/download-artifact@v3
        with:
          name: derived_data.zip
          path: builds/derived_data.zip
      - name: Unzip derived data
        run: unzip builds/derived_data.zip -d ./derived_data
      - name: Display derived data structure
        run: ls -R
        working-directory: derived_data
      - name: Run unit tests
        run: fastlane ci_unit_test
      - name: Report test results
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: ./builds/CILab.xcresult
        if: success() || failure()
